server:
  address: localhost
  port: 7070
  session:
    cookie:
      name: CLIENTSESSION

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
      userLogoutUri: http://localhost:8081/auth/logout
    resource:
      userInfoUri: http://localhost:8082/user/userinfo

ribbon:
  eureka:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health

spring:
  application:
    name: client-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    ipAddress: ${server.address}
    instanceId: ${server.address}:${server.port}