server:
  address: localhost
  port: 8081
  servlet:
    contextPath: /auth

spring:
  application:
    name: authorization-server
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  datasource:
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

ribbon:
  eureka:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    ipAddress: ${server.address}
    instanceId: ${server.address}:${server.port}